<?php
namespace AwsWPTC\Schemas;

use AwsWPTC\AwsClient;

/**
 * This client is used to interact with the **Schemas** service.
 * @method \AwsWPTC\Result createDiscoverer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createDiscovererAsync(array $args = [])
 * @method \AwsWPTC\Result createRegistry(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createRegistryAsync(array $args = [])
 * @method \AwsWPTC\Result createSchema(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createSchemaAsync(array $args = [])
 * @method \AwsWPTC\Result deleteDiscoverer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteDiscovererAsync(array $args = [])
 * @method \AwsWPTC\Result deleteRegistry(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteRegistryAsync(array $args = [])
 * @method \AwsWPTC\Result deleteResourcePolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteResourcePolicyAsync(array $args = [])
 * @method \AwsWPTC\Result deleteSchema(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteSchemaAsync(array $args = [])
 * @method \AwsWPTC\Result deleteSchemaVersion(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteSchemaVersionAsync(array $args = [])
 * @method \AwsWPTC\Result describeCodeBinding(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeCodeBindingAsync(array $args = [])
 * @method \AwsWPTC\Result describeDiscoverer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeDiscovererAsync(array $args = [])
 * @method \AwsWPTC\Result describeRegistry(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeRegistryAsync(array $args = [])
 * @method \AwsWPTC\Result describeSchema(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeSchemaAsync(array $args = [])
 * @method \AwsWPTC\Result getCodeBindingSource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getCodeBindingSourceAsync(array $args = [])
 * @method \AwsWPTC\Result getDiscoveredSchema(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getDiscoveredSchemaAsync(array $args = [])
 * @method \AwsWPTC\Result getResourcePolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getResourcePolicyAsync(array $args = [])
 * @method \AwsWPTC\Result listDiscoverers(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listDiscoverersAsync(array $args = [])
 * @method \AwsWPTC\Result listRegistries(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listRegistriesAsync(array $args = [])
 * @method \AwsWPTC\Result listSchemaVersions(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listSchemaVersionsAsync(array $args = [])
 * @method \AwsWPTC\Result listSchemas(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listSchemasAsync(array $args = [])
 * @method \AwsWPTC\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \AwsWPTC\Result putCodeBinding(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise putCodeBindingAsync(array $args = [])
 * @method \AwsWPTC\Result putResourcePolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise putResourcePolicyAsync(array $args = [])
 * @method \AwsWPTC\Result searchSchemas(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise searchSchemasAsync(array $args = [])
 * @method \AwsWPTC\Result startDiscoverer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise startDiscovererAsync(array $args = [])
 * @method \AwsWPTC\Result stopDiscoverer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise stopDiscovererAsync(array $args = [])
 * @method \AwsWPTC\Result tagResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise tagResourceAsync(array $args = [])
 * @method \AwsWPTC\Result untagResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise untagResourceAsync(array $args = [])
 * @method \AwsWPTC\Result updateDiscoverer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateDiscovererAsync(array $args = [])
 * @method \AwsWPTC\Result updateRegistry(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateRegistryAsync(array $args = [])
 * @method \AwsWPTC\Result updateSchema(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateSchemaAsync(array $args = [])
 * @method \AwsWPTC\Result exportSchema(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise exportSchemaAsync(array $args = [])
 */
class SchemasClient extends AwsClient {}
