<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'WP_Typography\\Vendor\\Masterminds\\' => array($vendorDir . '/masterminds/html5/src'),
    'WP_Typography\\Vendor\\Dice\\' => array($vendorDir . '/level-2/dice'),
);
