<?php
namespace AwsWPTC\ServiceDiscovery;

use AwsWPTC\AwsClient;

/**
 * This client is used to interact with the **Amazon Route 53 Auto Naming** service.
 * @method \AwsWPTC\Result createHttpNamespace(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createHttpNamespaceAsync(array $args = [])
 * @method \AwsWPTC\Result createPrivateDnsNamespace(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createPrivateDnsNamespaceAsync(array $args = [])
 * @method \AwsWPTC\Result createPublicDnsNamespace(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createPublicDnsNamespaceAsync(array $args = [])
 * @method \AwsWPTC\Result createService(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createServiceAsync(array $args = [])
 * @method \AwsWPTC\Result deleteNamespace(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteNamespaceAsync(array $args = [])
 * @method \AwsWPTC\Result deleteService(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteServiceAsync(array $args = [])
 * @method \AwsWPTC\Result deregisterInstance(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deregisterInstanceAsync(array $args = [])
 * @method \AwsWPTC\Result discoverInstances(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise discoverInstancesAsync(array $args = [])
 * @method \AwsWPTC\Result getInstance(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getInstanceAsync(array $args = [])
 * @method \AwsWPTC\Result getInstancesHealthStatus(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getInstancesHealthStatusAsync(array $args = [])
 * @method \AwsWPTC\Result getNamespace(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getNamespaceAsync(array $args = [])
 * @method \AwsWPTC\Result getOperation(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getOperationAsync(array $args = [])
 * @method \AwsWPTC\Result getService(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getServiceAsync(array $args = [])
 * @method \AwsWPTC\Result listInstances(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listInstancesAsync(array $args = [])
 * @method \AwsWPTC\Result listNamespaces(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listNamespacesAsync(array $args = [])
 * @method \AwsWPTC\Result listOperations(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listOperationsAsync(array $args = [])
 * @method \AwsWPTC\Result listServices(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listServicesAsync(array $args = [])
 * @method \AwsWPTC\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \AwsWPTC\Result registerInstance(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise registerInstanceAsync(array $args = [])
 * @method \AwsWPTC\Result tagResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise tagResourceAsync(array $args = [])
 * @method \AwsWPTC\Result untagResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise untagResourceAsync(array $args = [])
 * @method \AwsWPTC\Result updateHttpNamespace(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateHttpNamespaceAsync(array $args = [])
 * @method \AwsWPTC\Result updateInstanceCustomHealthStatus(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateInstanceCustomHealthStatusAsync(array $args = [])
 * @method \AwsWPTC\Result updatePrivateDnsNamespace(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updatePrivateDnsNamespaceAsync(array $args = [])
 * @method \AwsWPTC\Result updatePublicDnsNamespace(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updatePublicDnsNamespaceAsync(array $args = [])
 * @method \AwsWPTC\Result updateService(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateServiceAsync(array $args = [])
 */
class ServiceDiscoveryClient extends AwsClient {}
