<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbef47250909618e625a355af2afc0e22
{
    public static $prefixLengthsPsr4 = array (
        'K' => 
        array (
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\WpApi\\' => 42,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\' => 48,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\' => 49,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\' => 58,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\' => 58,
            'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\' => 40,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WpApi\\' => 
        array (
            0 => __DIR__ . '/..' . '/krokedil/wp-api/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\' => 
        array (
            0 => __DIR__ . '/..' . '/krokedil/woocommerce/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\' => 
        array (
            0 => __DIR__ . '/..' . '/krokedil/settings-page/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\' => 
        array (
            0 => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\' => 
        array (
            0 => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\BeforeValidException' => __DIR__ . '/..' . '/firebase/php-jwt/src/BeforeValidException.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\CachedKeySet' => __DIR__ . '/..' . '/firebase/php-jwt/src/CachedKeySet.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\ExpiredException' => __DIR__ . '/..' . '/firebase/php-jwt/src/ExpiredException.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\JWK' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWK.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\JWT' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWT.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\JWTExceptionWithPayloadInterface' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWTExceptionWithPayloadInterface.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\Key' => __DIR__ . '/..' . '/firebase/php-jwt/src/Key.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\SignatureInvalidException' => __DIR__ . '/..' . '/firebase/php-jwt/src/SignatureInvalidException.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\AJAX' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/AJAX.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Assets' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Assets.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\ClientTokenParser' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/ClientTokenParser.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\KlarnaExpressCheckout' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/KlarnaExpressCheckout.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Session' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Session.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Settings' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Settings.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\KlarnaOnsiteMessaging' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/KlarnaOnsiteMessaging.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Pages\\Cart' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Pages/Cart.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Pages\\Page' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Pages/Page.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Pages\\Product' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Pages/Product.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Settings' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Settings.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Shortcode' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Shortcode.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Utility' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Utility.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Widget' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Widget.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Addons' => __DIR__ . '/..' . '/krokedil/settings-page/src/Addons.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Gateway' => __DIR__ . '/..' . '/krokedil/settings-page/src/Gateway.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Navigation' => __DIR__ . '/..' . '/krokedil/settings-page/src/Navigation.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Page' => __DIR__ . '/..' . '/krokedil/settings-page/src/Page.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\SettingsPage' => __DIR__ . '/..' . '/krokedil/settings-page/src/SettingsPage.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Support' => __DIR__ . '/..' . '/krokedil/settings-page/src/Support.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Traits\\Layout' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Layout.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Traits\\Sidebar' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Sidebar.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Traits\\Singleton' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Singleton.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Traits\\Subsection' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Subsection.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Base' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Base.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\Cart' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/Cart.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\CartCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartCustomer.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\CartLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineCoupon.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\CartLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineFee.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\CartLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineItem.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\CartLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineShipping.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Abstracts\\AbstractGiftCardCompatibility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Abstracts/AbstractGiftCardCompatibility.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Compatibility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Compatibility.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\PWGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/PWGiftCards.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\SmartCoupons' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/SmartCoupons.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\WCGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/WCGiftCards.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\YITHGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/YITHGiftCards.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\CustomerData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/CustomerData.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Interfaces\\CompatibilityInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/CompatibilityInterface.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Interfaces\\GiftCardCompatibilityInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/GiftCardCompatibilityInterface.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Interfaces\\MetaboxInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/MetaboxInterface.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\KrokedilWooCommerce' => __DIR__ . '/..' . '/krokedil/woocommerce/src/KrokedilWooCommerce.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\OrderData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderData.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\OrderLineData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderLineData.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\OrderMetabox' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderMetabox.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\Order' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/Order.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderCustomer.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderLine' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLine.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineCoupon.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineFee.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineItem.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineShipping.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApi' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApi.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiCustomer.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineCoupon.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineFee.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineItem.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineShipping.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WpApi\\Logger' => __DIR__ . '/..' . '/krokedil/wp-api/src/Logger.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WpApi\\Request' => __DIR__ . '/..' . '/krokedil/wp-api/src/Request.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbef47250909618e625a355af2afc0e22::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbef47250909618e625a355af2afc0e22::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbef47250909618e625a355af2afc0e22::$classMap;

        }, null, ClassLoader::class);
    }
}
