<?php
namespace AwsWPTC\Transfer;

use AwsWPTC\AwsClient;

/**
 * This client is used to interact with the **AWS Transfer for SFTP** service.
 * @method \AwsWPTC\Result createAccess(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createAccessAsync(array $args = [])
 * @method \AwsWPTC\Result createServer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createServerAsync(array $args = [])
 * @method \AwsWPTC\Result createUser(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createUserAsync(array $args = [])
 * @method \AwsWPTC\Result deleteAccess(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteAccessAsync(array $args = [])
 * @method \AwsWPTC\Result deleteServer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteServerAsync(array $args = [])
 * @method \AwsWPTC\Result deleteSshPublicKey(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteSshPublicKeyAsync(array $args = [])
 * @method \AwsWPTC\Result deleteUser(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteUserAsync(array $args = [])
 * @method \AwsWPTC\Result describeAccess(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeAccessAsync(array $args = [])
 * @method \AwsWPTC\Result describeSecurityPolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeSecurityPolicyAsync(array $args = [])
 * @method \AwsWPTC\Result describeServer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeServerAsync(array $args = [])
 * @method \AwsWPTC\Result describeUser(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeUserAsync(array $args = [])
 * @method \AwsWPTC\Result importSshPublicKey(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise importSshPublicKeyAsync(array $args = [])
 * @method \AwsWPTC\Result listAccesses(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listAccessesAsync(array $args = [])
 * @method \AwsWPTC\Result listSecurityPolicies(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listSecurityPoliciesAsync(array $args = [])
 * @method \AwsWPTC\Result listServers(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listServersAsync(array $args = [])
 * @method \AwsWPTC\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \AwsWPTC\Result listUsers(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listUsersAsync(array $args = [])
 * @method \AwsWPTC\Result startServer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise startServerAsync(array $args = [])
 * @method \AwsWPTC\Result stopServer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise stopServerAsync(array $args = [])
 * @method \AwsWPTC\Result tagResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise tagResourceAsync(array $args = [])
 * @method \AwsWPTC\Result testIdentityProvider(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise testIdentityProviderAsync(array $args = [])
 * @method \AwsWPTC\Result untagResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise untagResourceAsync(array $args = [])
 * @method \AwsWPTC\Result updateAccess(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateAccessAsync(array $args = [])
 * @method \AwsWPTC\Result updateServer(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateServerAsync(array $args = [])
 * @method \AwsWPTC\Result updateUser(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateUserAsync(array $args = [])
 */
class TransferClient extends AwsClient {}
