<?php
namespace AwsWPTC\NetworkFirewall;

use AwsWPTC\AwsClient;

/**
 * This client is used to interact with the **AWS Network Firewall** service.
 * @method \AwsWPTC\Result associateFirewallPolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise associateFirewallPolicyAsync(array $args = [])
 * @method \AwsWPTC\Result associateSubnets(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise associateSubnetsAsync(array $args = [])
 * @method \AwsWPTC\Result createFirewall(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createFirewallAsync(array $args = [])
 * @method \AwsWPTC\Result createFirewallPolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createFirewallPolicyAsync(array $args = [])
 * @method \AwsWPTC\Result createRuleGroup(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createRuleGroupAsync(array $args = [])
 * @method \AwsWPTC\Result deleteFirewall(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteFirewallAsync(array $args = [])
 * @method \AwsWPTC\Result deleteFirewallPolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteFirewallPolicyAsync(array $args = [])
 * @method \AwsWPTC\Result deleteResourcePolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteResourcePolicyAsync(array $args = [])
 * @method \AwsWPTC\Result deleteRuleGroup(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteRuleGroupAsync(array $args = [])
 * @method \AwsWPTC\Result describeFirewall(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeFirewallAsync(array $args = [])
 * @method \AwsWPTC\Result describeFirewallPolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeFirewallPolicyAsync(array $args = [])
 * @method \AwsWPTC\Result describeLoggingConfiguration(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeLoggingConfigurationAsync(array $args = [])
 * @method \AwsWPTC\Result describeResourcePolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeResourcePolicyAsync(array $args = [])
 * @method \AwsWPTC\Result describeRuleGroup(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise describeRuleGroupAsync(array $args = [])
 * @method \AwsWPTC\Result disassociateSubnets(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise disassociateSubnetsAsync(array $args = [])
 * @method \AwsWPTC\Result listFirewallPolicies(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listFirewallPoliciesAsync(array $args = [])
 * @method \AwsWPTC\Result listFirewalls(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listFirewallsAsync(array $args = [])
 * @method \AwsWPTC\Result listRuleGroups(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listRuleGroupsAsync(array $args = [])
 * @method \AwsWPTC\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \AwsWPTC\Result putResourcePolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise putResourcePolicyAsync(array $args = [])
 * @method \AwsWPTC\Result tagResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise tagResourceAsync(array $args = [])
 * @method \AwsWPTC\Result untagResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise untagResourceAsync(array $args = [])
 * @method \AwsWPTC\Result updateFirewallDeleteProtection(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateFirewallDeleteProtectionAsync(array $args = [])
 * @method \AwsWPTC\Result updateFirewallDescription(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateFirewallDescriptionAsync(array $args = [])
 * @method \AwsWPTC\Result updateFirewallPolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateFirewallPolicyAsync(array $args = [])
 * @method \AwsWPTC\Result updateFirewallPolicyChangeProtection(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateFirewallPolicyChangeProtectionAsync(array $args = [])
 * @method \AwsWPTC\Result updateLoggingConfiguration(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateLoggingConfigurationAsync(array $args = [])
 * @method \AwsWPTC\Result updateRuleGroup(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateRuleGroupAsync(array $args = [])
 * @method \AwsWPTC\Result updateSubnetChangeProtection(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateSubnetChangeProtectionAsync(array $args = [])
 */
class NetworkFirewallClient extends AwsClient {}
