<?php
namespace AwsWPTC\RAM;

use AwsWPTC\AwsClient;

/**
 * This client is used to interact with the **AWS Resource Access Manager** service.
 * @method \AwsWPTC\Result acceptResourceShareInvitation(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise acceptResourceShareInvitationAsync(array $args = [])
 * @method \AwsWPTC\Result associateResourceShare(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise associateResourceShareAsync(array $args = [])
 * @method \AwsWPTC\Result associateResourceSharePermission(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise associateResourceSharePermissionAsync(array $args = [])
 * @method \AwsWPTC\Result createResourceShare(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise createResourceShareAsync(array $args = [])
 * @method \AwsWPTC\Result deleteResourceShare(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise deleteResourceShareAsync(array $args = [])
 * @method \AwsWPTC\Result disassociateResourceShare(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise disassociateResourceShareAsync(array $args = [])
 * @method \AwsWPTC\Result disassociateResourceSharePermission(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise disassociateResourceSharePermissionAsync(array $args = [])
 * @method \AwsWPTC\Result enableSharingWithAwsOrganization(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise enableSharingWithAwsOrganizationAsync(array $args = [])
 * @method \AwsWPTC\Result getPermission(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getPermissionAsync(array $args = [])
 * @method \AwsWPTC\Result getResourcePolicies(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getResourcePoliciesAsync(array $args = [])
 * @method \AwsWPTC\Result getResourceShareAssociations(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getResourceShareAssociationsAsync(array $args = [])
 * @method \AwsWPTC\Result getResourceShareInvitations(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getResourceShareInvitationsAsync(array $args = [])
 * @method \AwsWPTC\Result getResourceShares(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise getResourceSharesAsync(array $args = [])
 * @method \AwsWPTC\Result listPendingInvitationResources(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listPendingInvitationResourcesAsync(array $args = [])
 * @method \AwsWPTC\Result listPermissions(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listPermissionsAsync(array $args = [])
 * @method \AwsWPTC\Result listPrincipals(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listPrincipalsAsync(array $args = [])
 * @method \AwsWPTC\Result listResourceSharePermissions(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listResourceSharePermissionsAsync(array $args = [])
 * @method \AwsWPTC\Result listResourceTypes(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listResourceTypesAsync(array $args = [])
 * @method \AwsWPTC\Result listResources(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise listResourcesAsync(array $args = [])
 * @method \AwsWPTC\Result promoteResourceShareCreatedFromPolicy(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise promoteResourceShareCreatedFromPolicyAsync(array $args = [])
 * @method \AwsWPTC\Result rejectResourceShareInvitation(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise rejectResourceShareInvitationAsync(array $args = [])
 * @method \AwsWPTC\Result tagResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise tagResourceAsync(array $args = [])
 * @method \AwsWPTC\Result untagResource(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise untagResourceAsync(array $args = [])
 * @method \AwsWPTC\Result updateResourceShare(array $args = [])
 * @method \GuzzleHttpWPTC\Promise\Promise updateResourceShareAsync(array $args = [])
 */
class RAMClient extends AwsClient {}
