<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'SymfonyWPTC\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfonywptc/polyfill-mbstring'),
    'PsrWPTC\\Http\\Message\\' => array($vendorDir . '/psrwptc/http-message/src'),
    'PsrWPTC\\Http\\Client\\' => array($vendorDir . '/psrwptc/http-client/src'),
    'JmesPathWPTC\\' => array($vendorDir . '/mtdowlingwptc/jmespath.php/src'),
    'GuzzleHttpWPTC\\Psr7\\' => array($vendorDir . '/guzzlehttpwptc/psr7/src'),
    'GuzzleHttpWPTC\\Promise\\' => array($vendorDir . '/guzzlehttpwptc/promises/src'),
    'GuzzleHttpWPTC\\' => array($vendorDir . '/guzzlehttpwptc/guzzle/src'),
    'AwsWPTC\\' => array($vendorDir . '/awswptc/aws-sdk-php/src'),
);
