<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '7b11c4dc42b3b3023073cb14e519683cwptc' => $vendorDir . '/ralouphiewptc/getallheaders/src/getallheaders.php',
    'a0edc8309cc5e1d60e3047b5df6b7052wptc' => $vendorDir . '/guzzlehttpwptc/psr7/src/functions_include.php',
    'c964ee0ededf28c96ebd9db5099ef910wptc' => $vendorDir . '/guzzlehttpwptc/promises/src/functions_include.php',
    '0e6d7bf4a5811bfa5cf40c5ccd6fae6awptc' => $vendorDir . '/symfonywptc/polyfill-mbstring/bootstrap.php',
    'b067bc7112e384b61c701452d53a14a8wptc' => $vendorDir . '/mtdowlingwptc/jmespath.php/src/JmesPath.php',
    '37a3dc5111fe8f707ab4c132ef1dbc62wptc' => $vendorDir . '/guzzlehttpwptc/guzzle/src/functions_include.php',
    '8a9dc1de0ca7e01f3e08231539562f61wptc' => $vendorDir . '/awswptc/aws-sdk-php/src/functions.php',
);
