<?php

// autoload_static.php @generated by Composer

namespace ComposerWPTC\Autoload;

class ComposerStaticInitd59cb122d8712fcc2ed4ccdabaa0dd63
{
    public static $files = array (
        '7b11c4dc42b3b3023073cb14e519683cwptc' => __DIR__ . '/..' . '/ralouphiewptc/getallheaders/src/getallheaders.php',
        'a0edc8309cc5e1d60e3047b5df6b7052wptc' => __DIR__ . '/..' . '/guzzlehttpwptc/psr7/src/functions_include.php',
        'c964ee0ededf28c96ebd9db5099ef910wptc' => __DIR__ . '/..' . '/guzzlehttpwptc/promises/src/functions_include.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6awptc' => __DIR__ . '/..' . '/symfonywptc/polyfill-mbstring/bootstrap.php',
        'b067bc7112e384b61c701452d53a14a8wptc' => __DIR__ . '/..' . '/mtdowlingwptc/jmespath.php/src/JmesPath.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62wptc' => __DIR__ . '/..' . '/guzzlehttpwptc/guzzle/src/functions_include.php',
        '8a9dc1de0ca7e01f3e08231539562f61wptc' => __DIR__ . '/..' . '/awswptc/aws-sdk-php/src/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SymfonyWPTC\\Polyfill\\Mbstring\\' => 26,
        ),
        'P' => 
        array (
            'PsrWPTC\\Http\\Message\\' => 17,
            'PsrWPTC\\Http\\Client\\' => 16,
        ),
        'J' => 
        array (
            'JmesPathWPTC\\' => 9,
        ),
        'G' => 
        array (
            'GuzzleHttpWPTC\\Psr7\\' => 16,
            'GuzzleHttpWPTC\\Promise\\' => 19,
            'GuzzleHttpWPTC\\' => 11,
        ),
        'A' => 
        array (
            'AwsWPTC\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SymfonyWPTC\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfonywptc/polyfill-mbstring',
        ),
        'PsrWPTC\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psrwptc/http-message/src',
        ),
        'PsrWPTC\\Http\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/psrwptc/http-client/src',
        ),
        'JmesPathWPTC\\' => 
        array (
            0 => __DIR__ . '/..' . '/mtdowlingwptc/jmespath.php/src',
        ),
        'GuzzleHttpWPTC\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttpwptc/psr7/src',
        ),
        'GuzzleHttpWPTC\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttpwptc/promises/src',
        ),
        'GuzzleHttpWPTC\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttpwptc/guzzle/src',
        ),
        'AwsWPTC\\' => 
        array (
            0 => __DIR__ . '/..' . '/awswptc/aws-sdk-php/src',
        ),
    );

    public static $classMap = array (
        'ComposerWPTC\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd59cb122d8712fcc2ed4ccdabaa0dd63::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd59cb122d8712fcc2ed4ccdabaa0dd63::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd59cb122d8712fcc2ed4ccdabaa0dd63::$classMap;

        }, null, ClassLoader::class);
    }
}
