<?php

// scoper-autoload.php @generated by PhpScoper

$loader = require_once __DIR__.'/autoload.php';

// Exposed classes. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#exposing-classes
if (!class_exists('PHP_Typography\Fixes\Token_Fix', false) && !interface_exists('PHP_Typography\Fixes\Token_Fix', false) && !trait_exists('PHP_Typography\Fixes\Token_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Default_Registry', false) && !interface_exists('PHP_Typography\Fixes\Default_Registry', false) && !trait_exists('PHP_Typography\Fixes\Default_Registry', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Default_Registry');
}
if (!class_exists('PHP_Typography\Fixes\Token_Fixes\Hyphenate_Fix', false) && !interface_exists('PHP_Typography\Fixes\Token_Fixes\Hyphenate_Fix', false) && !trait_exists('PHP_Typography\Fixes\Token_Fixes\Hyphenate_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Hyphenate_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Token_Fixes\Hyphenate_Compounds_Fix', false) && !interface_exists('PHP_Typography\Fixes\Token_Fixes\Hyphenate_Compounds_Fix', false) && !trait_exists('PHP_Typography\Fixes\Token_Fixes\Hyphenate_Compounds_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Hyphenate_Compounds_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Token_Fixes\Smart_Dashes_Hyphen_Fix', false) && !interface_exists('PHP_Typography\Fixes\Token_Fixes\Smart_Dashes_Hyphen_Fix', false) && !trait_exists('PHP_Typography\Fixes\Token_Fixes\Smart_Dashes_Hyphen_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Smart_Dashes_Hyphen_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Token_Fixes\Abstract_Token_Fix', false) && !interface_exists('PHP_Typography\Fixes\Token_Fixes\Abstract_Token_Fix', false) && !trait_exists('PHP_Typography\Fixes\Token_Fixes\Abstract_Token_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Abstract_Token_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Token_Fixes\Wrap_URLs_Fix', false) && !interface_exists('PHP_Typography\Fixes\Token_Fixes\Wrap_URLs_Fix', false) && !trait_exists('PHP_Typography\Fixes\Token_Fixes\Wrap_URLs_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Wrap_URLs_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Token_Fixes\Wrap_Emails_Fix', false) && !interface_exists('PHP_Typography\Fixes\Token_Fixes\Wrap_Emails_Fix', false) && !trait_exists('PHP_Typography\Fixes\Token_Fixes\Wrap_Emails_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Wrap_Emails_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Token_Fixes\Wrap_Hard_Hyphens_Fix', false) && !interface_exists('PHP_Typography\Fixes\Token_Fixes\Wrap_Hard_Hyphens_Fix', false) && !trait_exists('PHP_Typography\Fixes\Token_Fixes\Wrap_Hard_Hyphens_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Token_Fixes\Wrap_Hard_Hyphens_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Registry', false) && !interface_exists('PHP_Typography\Fixes\Registry', false) && !trait_exists('PHP_Typography\Fixes\Registry', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Registry');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Space_Collapse_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Space_Collapse_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Space_Collapse_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Space_Collapse_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Fractions_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Fractions_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Fractions_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Fractions_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Dash_Spacing_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Dash_Spacing_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Dash_Spacing_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Dash_Spacing_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Dewidow_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Dewidow_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Dewidow_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Dewidow_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Style_Numbers_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Style_Numbers_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Style_Numbers_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Style_Numbers_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Maths_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Maths_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Maths_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Maths_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Diacritics_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Diacritics_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Diacritics_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Diacritics_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Ordinal_Suffix_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Ordinal_Suffix_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Ordinal_Suffix_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Ordinal_Suffix_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Process_Words_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Process_Words_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Process_Words_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Process_Words_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Area_Units_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Area_Units_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Area_Units_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Area_Units_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Style_Hanging_Punctuation_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Style_Hanging_Punctuation_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Style_Hanging_Punctuation_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Style_Hanging_Punctuation_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Simple_Style_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Simple_Style_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Simple_Style_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Simple_Style_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Quotes_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Quotes_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Quotes_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Quotes_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Exponents_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Exponents_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Exponents_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Exponents_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Style_Caps_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Style_Caps_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Style_Caps_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Style_Caps_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Single_Character_Word_Spacing_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Single_Character_Word_Spacing_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Single_Character_Word_Spacing_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Single_Character_Word_Spacing_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Numbered_Abbreviation_Spacing_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Numbered_Abbreviation_Spacing_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Numbered_Abbreviation_Spacing_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Numbered_Abbreviation_Spacing_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Abstract_Node_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Abstract_Node_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Abstract_Node_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Abstract_Node_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Unit_Spacing_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Unit_Spacing_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Unit_Spacing_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Unit_Spacing_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Dashes_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Dashes_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Dashes_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Dashes_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Style_Initial_Quotes_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Style_Initial_Quotes_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Style_Initial_Quotes_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Style_Initial_Quotes_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\French_Punctuation_Spacing_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\French_Punctuation_Spacing_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\French_Punctuation_Spacing_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\French_Punctuation_Spacing_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Marks_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Marks_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Marks_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Marks_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Style_Ampersands_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Style_Ampersands_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Style_Ampersands_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Style_Ampersands_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Simple_Regex_Replacement_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Simple_Regex_Replacement_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Simple_Regex_Replacement_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Simple_Regex_Replacement_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Classes_Dependent_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Classes_Dependent_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Classes_Dependent_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Classes_Dependent_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Ellipses_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Ellipses_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fixes\Smart_Ellipses_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fixes\Smart_Ellipses_Fix');
}
if (!class_exists('PHP_Typography\Fixes\Node_Fix', false) && !interface_exists('PHP_Typography\Fixes\Node_Fix', false) && !trait_exists('PHP_Typography\Fixes\Node_Fix', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Fixes\Node_Fix');
}
if (!class_exists('PHP_Typography\Settings\Simple_Quotes', false) && !interface_exists('PHP_Typography\Settings\Simple_Quotes', false) && !trait_exists('PHP_Typography\Settings\Simple_Quotes', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Settings\Simple_Quotes');
}
if (!class_exists('PHP_Typography\Settings\Simple_Dashes', false) && !interface_exists('PHP_Typography\Settings\Simple_Dashes', false) && !trait_exists('PHP_Typography\Settings\Simple_Dashes', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Settings\Simple_Dashes');
}
if (!class_exists('PHP_Typography\Settings\Quote_Style', false) && !interface_exists('PHP_Typography\Settings\Quote_Style', false) && !trait_exists('PHP_Typography\Settings\Quote_Style', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Settings\Quote_Style');
}
if (!class_exists('PHP_Typography\Settings\Quotes', false) && !interface_exists('PHP_Typography\Settings\Quotes', false) && !trait_exists('PHP_Typography\Settings\Quotes', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Settings\Quotes');
}
if (!class_exists('PHP_Typography\Settings\Dashes', false) && !interface_exists('PHP_Typography\Settings\Dashes', false) && !trait_exists('PHP_Typography\Settings\Dashes', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Settings\Dashes');
}
if (!class_exists('PHP_Typography\Settings\Dash_Style', false) && !interface_exists('PHP_Typography\Settings\Dash_Style', false) && !trait_exists('PHP_Typography\Settings\Dash_Style', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Settings\Dash_Style');
}
if (!class_exists('PHP_Typography\U', false) && !interface_exists('PHP_Typography\U', false) && !trait_exists('PHP_Typography\U', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\U');
}
if (!class_exists('PHP_Typography\RE', false) && !interface_exists('PHP_Typography\RE', false) && !trait_exists('PHP_Typography\RE', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\RE');
}
if (!class_exists('PHP_Typography\PHP_Typography', false) && !interface_exists('PHP_Typography\PHP_Typography', false) && !trait_exists('PHP_Typography\PHP_Typography', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\PHP_Typography');
}
if (!class_exists('PHP_Typography\Text_Parser', false) && !interface_exists('PHP_Typography\Text_Parser', false) && !trait_exists('PHP_Typography\Text_Parser', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Text_Parser');
}
if (!class_exists('PHP_Typography\Strings', false) && !interface_exists('PHP_Typography\Strings', false) && !trait_exists('PHP_Typography\Strings', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Strings');
}
if (!class_exists('PHP_Typography\Hyphenator\Trie_Node', false) && !interface_exists('PHP_Typography\Hyphenator\Trie_Node', false) && !trait_exists('PHP_Typography\Hyphenator\Trie_Node', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Hyphenator\Trie_Node');
}
if (!class_exists('PHP_Typography\Hyphenator\Cache', false) && !interface_exists('PHP_Typography\Hyphenator\Cache', false) && !trait_exists('PHP_Typography\Hyphenator\Cache', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Hyphenator\Cache');
}
if (!class_exists('PHP_Typography\Settings', false) && !interface_exists('PHP_Typography\Settings', false) && !trait_exists('PHP_Typography\Settings', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Settings');
}
if (!class_exists('PHP_Typography\DOM', false) && !interface_exists('PHP_Typography\DOM', false) && !trait_exists('PHP_Typography\DOM', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\DOM');
}
if (!class_exists('PHP_Typography\Hyphenator', false) && !interface_exists('PHP_Typography\Hyphenator', false) && !trait_exists('PHP_Typography\Hyphenator', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Hyphenator');
}
if (!class_exists('PHP_Typography\Text_Parser\Token', false) && !interface_exists('PHP_Typography\Text_Parser\Token', false) && !trait_exists('PHP_Typography\Text_Parser\Token', false)) {
    spl_autoload_call('WP_Typography\Vendor\PHP_Typography\Text_Parser\Token');
}

return $loader;
